-- Migration: plant_seeding_appartamento
-- Aggiunge la sezione "Appartamento" al catalogo con 50 piante da interno

INSERT INTO plant_knowledge (slug, specie_nome, growth_days, semina_mesi_esterno, semina_mesi_interno, specie_nome_scientifico, descrizione, annaffiatura, esposizione, tipo, difficolta, mesi_raccolta, piante_compagne, piante_incompatibili, attivita_suggerite)
VALUES

('monstera', 'Monstera', 1825, '{}', '{3,4,5}', 'Monstera deliciosa',
 'Rampicante tropicale con grandi foglie fenestrate, molto amata come pianta d''arredo.',
 'ogni 7 giorni, lasciare asciugare il terreno tra un''annaffiatura e l''altra', 'Luce indiretta intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}, {"nome": "Concimazione", "offset_days": 30, "recurrence_days": 30, "color": "green"}]'::jsonb),

('ficus_lyrata', 'Ficus lyrata', 1825, '{}', '{3,4,5}', 'Ficus lyrata',
 'Albero da interno con grandi foglie a forma di violino, molto scenografico.',
 'ogni 7-10 giorni, terreno leggermente umido', 'Luce indiretta intensa',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Concimazione", "offset_days": 30, "recurrence_days": 30, "color": "green"}]'::jsonb),

('ficus_elastica', 'Ficus elastica', 1825, '{}', '{3,4,5}', 'Ficus elastica',
 'Pianta da interno rustica con foglie lucide e coriacee, tollera l''ombra.',
 'ogni 7-10 giorni, lasciare asciugare in superficie', 'Luce indiretta',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Concimazione", "offset_days": 30, "recurrence_days": 30, "color": "green"}]'::jsonb),

('sansevieria', 'Sansevieria', 3650, '{}', '{3,4,5}', 'Dracaena trifasciata',
 'Pianta succulenta praticamente indistruttibile, purifica l''aria e tollera trascuratezza.',
 'ogni 15-20 giorni, molto tollerante alla siccità', 'Luce indiretta o scarsa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 18, "color": "blue"}]'::jsonb),

('pothos', 'Pothos', 1825, '{}', '{3,4,5}', 'Epipremnum aureum',
 'Rampicante a crescita rapidissima, ideale per principianti, si adatta a molte condizioni di luce.',
 'ogni 7 giorni, lasciare asciugare il terreno in superficie', 'Luce indiretta',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}]'::jsonb),

('filodendro', 'Filodendro rampicante', 1825, '{}', '{3,4,5}', 'Philodendron hederaceum',
 'Rampicante dalle foglie a cuore, molto tollerante e adatto ad ambienti poco luminosi.',
 'ogni 7 giorni, terreno leggermente umido', 'Luce indiretta',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}]'::jsonb),

('calathea_orbifolia', 'Calathea orbifolia', 1460, '{}', '{3,4,5}', 'Calathea orbifolia',
 'Pianta ornamentale con foglie striate argentee, richiede umidità elevata.',
 'ogni 4-5 giorni, terreno sempre leggermente umido', 'Luce indiretta',
 'appartamento', 'Difficile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 4, "color": "blue"}, {"nome": "Nebulizzazione", "offset_days": 0, "recurrence_days": 3, "color": "orange"}]'::jsonb),

('maranta', 'Maranta', 1460, '{}', '{3,4,5}', 'Maranta leuconeura',
 'Pianta della preghiera, foglie che si aprono e chiudono con la luce, ama l''umidità.',
 'ogni 5 giorni, terreno sempre umido', 'Luce indiretta',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 5, "color": "blue"}, {"nome": "Nebulizzazione", "offset_days": 0, "recurrence_days": 3, "color": "orange"}]'::jsonb),

('aloe_vera', 'Aloe vera', 3650, '{}', '{3,4,5}', 'Aloe vera',
 'Succulenta officinale dalle proprietà lenitive, richiede pochissima acqua.',
 'ogni 15-20 giorni, lasciare asciugare completamente', 'Pieno sole o luce intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 18, "color": "blue"}]'::jsonb),

('zamioculcas', 'Zamioculcas', 3650, '{}', '{3,4,5}', 'Zamioculcas zamiifolia',
 'Pianta rustica dalle foglie lucide, tollera ombra e siccità prolungata.',
 'ogni 15 giorni, lasciare asciugare completamente tra le annaffiature', 'Luce indiretta o scarsa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 15, "color": "blue"}]'::jsonb),

('spatifillo', 'Spatifillo', 1825, '{}', '{3,4,5}', 'Spathiphyllum wallisii',
 'Pianta da appartamento con fioritura bianca, segnala la sete abbassando le foglie.',
 'ogni 5-6 giorni, terreno sempre leggermente umido', 'Luce indiretta o scarsa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 5, "color": "blue"}, {"nome": "Concimazione", "offset_days": 30, "recurrence_days": 30, "color": "green"}]'::jsonb),

('dracena_marginata', 'Dracena marginata', 2555, '{}', '{3,4,5}', 'Dracaena marginata',
 'Pianta ornamentale dal fusto sottile e ciuffi di foglie sottili bordate di rosso.',
 'ogni 10 giorni, lasciare asciugare tra le annaffiature', 'Luce indiretta intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 10, "color": "blue"}]'::jsonb),

('tronchetto_felicita', 'Tronchetto della felicità', 2555, '{}', '{3,4,5}', 'Dracaena fragrans',
 'Pianta d''arredo classica, tronco legnoso e ciuffo di foglie striate.',
 'ogni 10 giorni, lasciare asciugare tra le annaffiature', 'Luce indiretta',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 10, "color": "blue"}]'::jsonb),

('yucca', 'Yucca', 3650, '{}', '{3,4,5}', 'Yucca elephantipes',
 'Pianta d''arredo dal fusto robusto e foglie a lancia, molto resistente alla siccità.',
 'ogni 12-15 giorni, lasciare asciugare completamente', 'Luce diretta o intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 13, "color": "blue"}]'::jsonb),

('palma_areca', 'Palma areca', 2555, '{}', '{3,4,5}', 'Dypsis lutescens',
 'Palma da interno elegante e frondosa, gradisce ambienti luminosi e umidità.',
 'ogni 6-7 giorni, terreno leggermente umido', 'Luce indiretta intensa',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}, {"nome": "Nebulizzazione", "offset_days": 0, "recurrence_days": 5, "color": "orange"}]'::jsonb),

('palma_kentia', 'Palma kentia', 2920, '{}', '{3,4,5}', 'Howea forsteriana',
 'Palma elegante molto tollerante alla scarsa luminosità, classica per interni.',
 'ogni 7-8 giorni, terreno leggermente umido', 'Luce indiretta',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}]'::jsonb),

('ficus_benjamin', 'Ficus benjamin', 2190, '{}', '{3,4,5}', 'Ficus benjamina',
 'Albero da interno molto diffuso, foglie piccole e lucide, sensibile agli spostamenti.',
 'ogni 7 giorni, terreno leggermente umido', 'Luce indiretta intensa',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}]'::jsonb),

('anthurium', 'Anthurium', 1460, '{}', '{3,4,5}', 'Anthurium andraeanum',
 'Pianta tropicale con spate colorate a forma di cuore, fiorisce quasi tutto l''anno.',
 'ogni 6 giorni, terreno sempre leggermente umido', 'Luce indiretta',
 'appartamento', 'Medio', '{1,2,3,4,5,6,7,8,9,10,11,12}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}, {"nome": "Concimazione", "offset_days": 30, "recurrence_days": 30, "color": "green"}]'::jsonb),

('orchidea_phalaenopsis', 'Orchidea Phalaenopsis', 1095, '{}', '{3,4,5}', 'Phalaenopsis spp.',
 'Orchidea da appartamento più diffusa, fioritura lunga e delicata.',
 'ogni 7-10 giorni per immersione, radici visibili aiutano a dosare', 'Luce indiretta intensa',
 'appartamento', 'Medio', '{1,2,3,4,5,6,7,8,9,10,11,12}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Concimazione", "offset_days": 30, "recurrence_days": 30, "color": "green"}]'::jsonb),

('croton', 'Croton', 1825, '{}', '{3,4,5}', 'Codiaeum variegatum',
 'Pianta ornamentale dal fogliame variegato rosso, giallo e verde, ama la luce.',
 'ogni 6 giorni, terreno leggermente umido', 'Luce diretta o intensa',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}]'::jsonb),

('fittonia', 'Fittonia', 1095, '{}', '{3,4,5}', 'Fittonia albivenis',
 'Piccola pianta tappezzante con foglie venate, richiede umidità costante.',
 'ogni 3-4 giorni, terreno sempre umido', 'Luce indiretta o scarsa',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 3, "color": "blue"}, {"nome": "Nebulizzazione", "offset_days": 0, "recurrence_days": 2, "color": "orange"}]'::jsonb),

('tillandsia', 'Tillandsia', 1095, '{}', '{3,4,5}', 'Tillandsia ionantha',
 'Pianta aerea senza radici in terra, assorbe acqua e nutrienti dall''aria.',
 'nebulizzazione ogni 3-4 giorni o immersione settimanale', 'Luce indiretta intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Nebulizzazione", "offset_days": 0, "recurrence_days": 4, "color": "orange"}]'::jsonb),

('echinocactus', 'Cactus a cuscino di suocera', 3650, '{}', '{3,4,5}', 'Echinocactus grusonii',
 'Cactus globoso a crescita lenta, coperto di spine dorate.',
 'ogni 20-25 giorni, lasciare asciugare completamente', 'Pieno sole',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 22, "color": "blue"}]'::jsonb),

('kalanchoe', 'Kalanchoe', 730, '{}', '{3,4,5}', 'Kalanchoe blossfeldiana',
 'Succulenta fiorifera dai colori vivaci, fioritura invernale prolungata.',
 'ogni 10 giorni, lasciare asciugare tra le annaffiature', 'Luce diretta o intensa',
 'appartamento', 'Facile', '{1,2,3,12}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 10, "color": "blue"}]'::jsonb),

('crassula_ovata', 'Albero di giada', 3650, '{}', '{3,4,5}', 'Crassula ovata',
 'Succulenta arborescente dalle foglie carnose, simbolo di prosperità.',
 'ogni 15 giorni, lasciare asciugare completamente', 'Luce diretta o intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 15, "color": "blue"}]'::jsonb),

('peperomia', 'Peperomia', 1095, '{}', '{3,4,5}', 'Peperomia obtusifolia',
 'Piccola pianta compatta dalle foglie carnose, adatta a spazi ridotti.',
 'ogni 7-9 giorni, lasciare asciugare in superficie', 'Luce indiretta',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}]'::jsonb),

('ciclamino', 'Ciclamino', 365, '{}', '{9,10}', 'Cyclamen persicum',
 'Pianta fiorifera invernale da interno fresco, fiori a farfalla su lunghi steli.',
 'ogni 4-5 giorni, evitare di bagnare il tubero', 'Luce indiretta intensa',
 'appartamento', 'Medio', '{11,12,1,2,3}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 4, "color": "blue"}]'::jsonb),

('begonia_maculata', 'Begonia maculata', 1095, '{}', '{3,4,5}', 'Begonia maculata',
 'Begonia ornamentale con foglie a pois argentati, molto decorativa.',
 'ogni 6 giorni, terreno leggermente umido', 'Luce indiretta intensa',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}]'::jsonb),

('alocasia', 'Alocasia', 1095, '{}', '{3,4,5}', 'Alocasia amazonica',
 'Pianta tropicale dalle grandi foglie scure a punta di freccia, ama umidità elevata.',
 'ogni 5 giorni, terreno sempre leggermente umido', 'Luce indiretta',
 'appartamento', 'Difficile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 5, "color": "blue"}, {"nome": "Nebulizzazione", "offset_days": 0, "recurrence_days": 3, "color": "orange"}]'::jsonb),

('nastrino', 'Nastrino', 1460, '{}', '{3,4,5}', 'Chlorophytum comosum',
 'Pianta ricadente molto rustica, produce stoloni con piccole piantine.',
 'ogni 7 giorni, terreno leggermente umido', 'Luce indiretta',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}]'::jsonb),

('tradescantia', 'Tradescantia zebrina', 1095, '{}', '{3,4,5}', 'Tradescantia zebrina',
 'Pianta ricadente a crescita rapida, foglie striate viola e argento.',
 'ogni 6 giorni, terreno leggermente umido', 'Luce indiretta intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}]'::jsonb),

('hoya', 'Hoya (fiore di cera)', 2555, '{}', '{3,4,5}', 'Hoya carnosa',
 'Rampicante succulento con fiori cerosi profumati a stella, crescita lenta.',
 'ogni 10 giorni, lasciare asciugare tra le annaffiature', 'Luce indiretta intensa',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 10, "color": "blue"}]'::jsonb),

('schefflera', 'Schefflera', 1825, '{}', '{3,4,5}', 'Schefflera arboricola',
 'Pianta d''arredo con foglie composte a ombrello, facile da coltivare.',
 'ogni 7-8 giorni, lasciare asciugare in superficie', 'Luce indiretta intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}]'::jsonb),

('felce_nido', 'Felce nido d''uccello', 1460, '{}', '{3,4,5}', 'Asplenium nidus',
 'Felce epifita dalle fronde larghe a rosetta, ama umidità e ombra.',
 'ogni 5 giorni, terreno sempre leggermente umido', 'Luce indiretta o scarsa',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 5, "color": "blue"}, {"nome": "Nebulizzazione", "offset_days": 0, "recurrence_days": 3, "color": "orange"}]'::jsonb),

('felce_boston', 'Felce di Boston', 1095, '{}', '{3,4,5}', 'Nephrolepis exaltata',
 'Felce classica dalle fronde arcuate e ricadenti, richiede umidità costante.',
 'ogni 4 giorni, terreno sempre umido', 'Luce indiretta',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 4, "color": "blue"}, {"nome": "Nebulizzazione", "offset_days": 0, "recurrence_days": 3, "color": "orange"}]'::jsonb),

('beaucarnea', 'Piede di elefante', 3650, '{}', '{3,4,5}', 'Beaucarnea recurvata',
 'Pianta dal fusto rigonfio alla base che accumula acqua, molto resistente.',
 'ogni 15-18 giorni, lasciare asciugare completamente', 'Luce diretta o intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 16, "color": "blue"}]'::jsonb),

('cycas', 'Cycas', 3650, '{}', '{3,4,5}', 'Cycas revoluta',
 'Pianta ornamentale a crescita lenta con foglie rigide simili a felci giganti.',
 'ogni 10-12 giorni, lasciare asciugare tra le annaffiature', 'Luce indiretta intensa',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 11, "color": "blue"}]'::jsonb),

('strelitzia', 'Strelitzia (uccello del paradiso)', 2555, '{}', '{3,4,5}', 'Strelitzia reginae',
 'Pianta ornamentale dai fiori esotici arancioni e blu a forma di uccello.',
 'ogni 6-7 giorni, terreno leggermente umido', 'Luce diretta o intensa',
 'appartamento', 'Medio', '{5,6,7,8,9}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}]'::jsonb),

('aglaonema', 'Aglaonema', 1460, '{}', '{3,4,5}', 'Aglaonema commutatum',
 'Pianta d''arredo con foglie variegate, molto tollerante alla scarsa luminosità.',
 'ogni 7 giorni, terreno leggermente umido', 'Luce indiretta o scarsa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}]'::jsonb),

('syngonium', 'Syngonium', 1460, '{}', '{3,4,5}', 'Syngonium podophyllum',
 'Rampicante dalle foglie a forma di freccia, crescita rapida e facile.',
 'ogni 6-7 giorni, terreno leggermente umido', 'Luce indiretta',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}]'::jsonb),

('pilea', 'Pilea (pianta delle monete)', 1095, '{}', '{3,4,5}', 'Pilea peperomioides',
 'Pianta compatta con foglie rotonde a moneta, produce facilmente polloni.',
 'ogni 7 giorni, lasciare asciugare in superficie', 'Luce indiretta intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}]'::jsonb),

('ficus_pumila', 'Ficus pumila', 1460, '{}', '{3,4,5}', 'Ficus pumila',
 'Rampicante tappezzante a foglie piccole, ideale per terrari e pareti verdi.',
 'ogni 5-6 giorni, terreno leggermente umido', 'Luce indiretta',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 5, "color": "blue"}]'::jsonb),

('euphorbia_trigona', 'Euphorbia trigona', 2555, '{}', '{3,4,5}', 'Euphorbia trigona',
 'Succulenta colonnare dall''aspetto simile a un cactus, linfa irritante.',
 'ogni 12-15 giorni, lasciare asciugare completamente', 'Luce diretta o intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 13, "color": "blue"}]'::jsonb),

('opuntia_microdasys', 'Fico d''india nano', 2920, '{}', '{3,4,5}', 'Opuntia microdasys',
 'Cactus a pale con piccole glochidi urticanti, molto resistente alla siccità.',
 'ogni 20 giorni, lasciare asciugare completamente', 'Pieno sole',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 20, "color": "blue"}]'::jsonb),

('haworthia', 'Haworthia', 2190, '{}', '{3,4,5}', 'Haworthia fasciata',
 'Piccola succulenta con foglie a rosetta striate di bianco, adatta a spazi piccoli.',
 'ogni 15 giorni, lasciare asciugare completamente', 'Luce indiretta intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 15, "color": "blue"}]'::jsonb),

('echeveria', 'Echeveria', 1825, '{}', '{3,4,5}', 'Echeveria elegans',
 'Succulenta a rosetta dalle foglie glauche, ideale per composizioni.',
 'ogni 12 giorni, lasciare asciugare completamente', 'Luce diretta o intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 12, "color": "blue"}]'::jsonb),

('sedum_morganianum', 'Rosario dell''amore', 1825, '{}', '{3,4,5}', 'Sedum morganianum',
 'Succulenta ricadente con foglioline a forma di goccia, ottima in cesti sospesi.',
 'ogni 14 giorni, lasciare asciugare completamente', 'Luce diretta o intensa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 14, "color": "blue"}]'::jsonb),

('sansevieria_cylindrica', 'Sansevieria cilindrica', 3650, '{}', '{3,4,5}', 'Dracaena angolensis',
 'Variante di sansevieria con foglie cilindriche a punta, molto resistente.',
 'ogni 18 giorni, molto tollerante alla siccità', 'Luce indiretta o scarsa',
 'appartamento', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 18, "color": "blue"}]'::jsonb),

('rhipsalis', 'Rhipsalis', 1825, '{}', '{3,4,5}', 'Rhipsalis baccifera',
 'Cactus epifita ricadente senza spine, adatto a cesti sospesi in ombra.',
 'ogni 7-8 giorni, terreno leggermente umido', 'Luce indiretta',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}]'::jsonb),

('cordyline', 'Cordyline', 1825, '{}', '{3,4,5}', 'Cordyline fruticosa',
 'Pianta ornamentale dalle foglie lanceolate rosse o variegate, effetto scenografico.',
 'ogni 6-7 giorni, terreno leggermente umido', 'Luce indiretta intensa',
 'appartamento', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}]'::jsonb)

ON CONFLICT (slug) DO NOTHING;
