-- Migration: plant_seeding_alberi_estesa
-- Espande la sezione "Albero" del catalogo con 50 nuove specie

INSERT INTO plant_knowledge (slug, specie_nome, growth_days, semina_mesi_esterno, semina_mesi_interno, specie_nome_scientifico, descrizione, annaffiatura, esposizione, tipo, difficolta, mesi_raccolta, piante_compagne, piante_incompatibili, attivita_suggerite)
VALUES

('faggio', 'Faggio', 3650, '{10,11,3,4}', '{}', 'Fagus sylvatica',
 'Albero maestoso a foglia caduca, chioma densa e ombreggiante. Predilige climi freschi e suoli profondi.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('betulla', 'Betulla', 1825, '{10,11,3,4}', '{}', 'Betula pendula',
 'Albero pioniere a crescita rapida, corteccia bianca caratteristica, foglie leggere.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('acero_campestre', 'Acero campestre', 2190, '{10,11,3,4}', '{}', 'Acer campestre',
 'Piccolo albero rustico usato in siepi e filari, ottima colorazione autunnale.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('acero_riccio', 'Acero riccio', 2555, '{10,11,3,4}', '{}', 'Acer platanoides',
 'Albero ornamentale con ampia chioma tondeggiante, foglie gialle in autunno.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('acero_rosso', 'Acero rosso', 2555, '{10,11,3,4}', '{}', 'Acer rubrum',
 'Albero nordamericano apprezzato per il fogliame rosso acceso in autunno.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole o mezza ombra',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('ontano_nero', 'Ontano nero', 1825, '{10,11,3,4}', '{}', 'Alnus glutinosa',
 'Albero igrofilo tipico di rive e zone umide, radici che fissano azoto.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 5, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('frassino_maggiore', 'Frassino maggiore', 2555, '{10,11,3,4}', '{}', 'Fraxinus excelsior',
 'Albero forestale a crescita rapida, legno elastico e pregiato.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('olmo_campestre', 'Olmo campestre', 2190, '{10,11,3,4}', '{}', 'Ulmus minor',
 'Albero rustico da filare, un tempo diffusissimo, oggi minacciato dalla grafiosi.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('carpino_bianco', 'Carpino bianco', 2190, '{10,11,3,4}', '{}', 'Carpinus betulus',
 'Albero ideale per siepi alte e filari, tollera bene le potature.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('castagno', 'Castagno', 3650, '{10,11,3,4}', '{}', 'Castanea sativa',
 'Albero da frutto e da legno, richiede terreni acidi e ben drenati.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 9, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('noce_comune', 'Noce comune', 3650, '{10,11,3,4}', '{}', 'Juglans regia',
 'Albero maestoso, radice allelopatica: mantenere distanza da altre colture.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 10, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('platano', 'Platano', 2920, '{10,11,3,4}', '{}', 'Platanus x acerifolia',
 'Albero da viale a crescita rapida, corteccia che si sfalda a placche.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('ippocastano', 'Ippocastano', 2555, '{10,11,3,4}', '{}', 'Aesculus hippocastanum',
 'Albero ornamentale con vistose infiorescenze bianche o rosa in primavera.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('salice_piangente', 'Salice piangente', 1460, '{2,3,10,11}', '{}', 'Salix babylonica',
 'Albero ornamentale dai rami ricadenti, ama i terreni umidi vicino all''acqua.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 4, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('salice_bianco', 'Salice bianco', 1460, '{2,3,10,11}', '{}', 'Salix alba',
 'Albero rustico a crescita rapida, tollera bene l''umidità del terreno.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 4, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('pino_domestico', 'Pino domestico', 3650, '{3,4,10}', '{}', 'Pinus pinea',
 'Conifera mediterranea dalla caratteristica chioma a ombrello, produce pinoli.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 12, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('pino_marittimo', 'Pino marittimo', 2920, '{3,4,10}', '{}', 'Pinus pinaster',
 'Conifera rustica adatta a terreni sabbiosi e costieri, resistente al vento.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 12, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('pino_silvestre', 'Pino silvestre', 2920, '{3,4,10}', '{}', 'Pinus sylvestris',
 'Conifera montana con corteccia rossastra, molto resistente al freddo.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 12, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('abete_rosso', 'Abete rosso', 2920, '{3,4,10}', '{}', 'Picea abies',
 'Conifera piramidale tipica delle Alpi, usata anche come albero di Natale.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole o mezza ombra',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 10, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('abete_bianco', 'Abete bianco', 3285, '{3,4,10}', '{}', 'Abies alba',
 'Conifera montana slanciata, richiede clima fresco e umido.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Mezza ombra',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 10, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('cipresso_comune', 'Cipresso comune', 2555, '{3,4,10}', '{}', 'Cupressus sempervirens',
 'Conifera mediterranea dal portamento colonnare, tipica dei viali toscani.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 10, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('cedro_libano', 'Cedro del Libano', 3650, '{3,4,10}', '{}', 'Cedrus libani',
 'Conifera maestosa a crescita lenta, chioma ampia e appiattita da adulta.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 10, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('ginkgo', 'Ginkgo', 2920, '{3,4,10,11}', '{}', 'Ginkgo biloba',
 'Albero ''fossile vivente'', foglie a ventaglio dorate in autunno, molto resistente.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('magnolia', 'Magnolia', 2190, '{3,4,10}', '{}', 'Magnolia grandiflora',
 'Albero sempreverde con grandi fiori bianchi profumati in estate.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole o mezza ombra',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('leccio', 'Leccio', 3650, '{10,11,3,4}', '{}', 'Quercus ilex',
 'Quercia sempreverde mediterranea, molto resistente a siccità e vento salmastro.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 12, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('sughera', 'Sughera', 3650, '{10,11,3,4}', '{}', 'Quercus suber',
 'Quercia sempreverde da cui si ricava il sughero, predilige terreni silicei.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 12, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('roverella', 'Roverella', 3650, '{10,11,3,4}', '{}', 'Quercus pubescens',
 'Quercia rustica tipica degli ambienti collinari mediterranei, molto resistente.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 12, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('cerro', 'Cerro', 3650, '{10,11,3,4}', '{}', 'Quercus cerris',
 'Quercia forestale a crescita relativamente rapida, ghiande grandi e ispide.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 12, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('corbezzolo', 'Corbezzolo', 1825, '{3,4,10}', '{}', 'Arbutus unedo',
 'Arbusto/alberello sempreverde mediterraneo, frutti rossi eduli in autunno.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('bagolaro', 'Bagolaro', 2555, '{10,11,3,4}', '{}', 'Celtis australis',
 'Albero da viale molto rustico e resistente all''inquinamento urbano.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 9, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('robinia', 'Robinia', 1460, '{10,11,3,4}', '{}', 'Robinia pseudoacacia',
 'Albero a crescita rapidissima, fiori bianchi profumati e mellifere.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('ailanto', 'Ailanto', 1095, '{3,4,10}', '{}', 'Ailanthus altissima',
 'Albero pioniere a crescitissima rapida, molto rustico ma invasivo.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 5, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('tamerice', 'Tamerice', 1460, '{3,4,10}', '{}', 'Tamarix gallica',
 'Arbusto/alberello resistente alla salsedine, ideale per zone costiere.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('larice', 'Larice', 2920, '{3,4,10}', '{}', 'Larix decidua',
 'Unica conifera europea a foglia caduca, tipica delle Alpi.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 9, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('douglasia', 'Douglasia', 2920, '{3,4,10}', '{}', 'Pseudotsuga menziesii',
 'Conifera nordamericana a crescita rapida, legno molto pregiato.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole o mezza ombra',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 9, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('sequoia', 'Sequoia sempreverde', 3650, '{3,4,10}', '{}', 'Sequoia sempervirens',
 'Conifera gigante a crescita rapida, tra le piante più alte al mondo.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 9, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('tasso', 'Tasso', 3650, '{3,4,10}', '{}', 'Taxus baccata',
 'Conifera sempreverde a crescita lenta, ottima per siepi topiarie; bacche tossiche.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Mezza ombra',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 9, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('ginepro_comune', 'Ginepro comune', 2555, '{3,4,10}', '{}', 'Juniperus communis',
 'Conifera arbustiva rustica, bacche usate in cucina e liquoreria.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 10, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('carrubo', 'Carrubo', 2920, '{3,4,10}', '{}', 'Ceratonia siliqua',
 'Albero sempreverde mediterraneo molto resistente alla siccità, baccelli eduli.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 14, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('eucalipto', 'Eucalipto', 1460, '{3,4,10}', '{}', 'Eucalyptus globulus',
 'Albero sempreverde a crescita rapidissima, foglie aromatiche.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('mimosa', 'Mimosa', 1095, '{3,4,10}', '{}', 'Acacia dealbata',
 'Albero a crescita rapida con vistosa fioritura gialla profumata a fine inverno.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('jacaranda', 'Jacaranda', 1825, '{3,4,5}', '{}', 'Jacaranda mimosifolia',
 'Albero ornamentale subtropicale con spettacolare fioritura blu-violetta.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('tiglio_argenteo', 'Tiglio argenteo', 2555, '{10,11,3,4}', '{}', 'Tilia tomentosa',
 'Albero ornamentale con foglie argentate nella pagina inferiore, molto mellifero.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('frassino_ornello', 'Frassino ornello', 2190, '{10,11,3,4}', '{}', 'Fraxinus ornus',
 'Piccolo albero rustico con vistose infiorescenze bianche profumate in primavera.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('olmo_montano', 'Olmo montano', 2190, '{10,11,3,4}', '{}', 'Ulmus glabra',
 'Albero forestale montano, chioma ampia e foglie grandi ruvide.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole o mezza ombra',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 8, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('carpino_nero', 'Carpino nero', 2555, '{10,11,3,4}', '{}', 'Ostrya carpinifolia',
 'Albero rustico dei versanti collinari, legno molto duro.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 9, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('nocciolo', 'Nocciolo', 1095, '{10,11,3,4}', '{}', 'Corylus avellana',
 'Arbusto/alberello coltivato per i frutti (nocciole) o come siepe ornamentale.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 6, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('palma_canarie', 'Palma delle Canarie', 2555, '{4,5,9}', '{}', 'Phoenix canariensis',
 'Palma ornamentale maestosa, adatta a climi miti e costieri.',
 'ogni 5-8 giorni nel primo anno, poi regolare nei periodi siccitosi', 'Pieno sole',
 'albero', 'Medio', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 10, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('ontano_bianco', 'Ontano bianco', 1825, '{10,11,3,4}', '{}', 'Alnus incana',
 'Albero pioniere rustico, tollera terreni umidi e poveri.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 5, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb),

('acero_negundo', 'Acero negundo', 1825, '{10,11,3,4}', '{}', 'Acer negundo',
 'Albero a crescita rapida molto rustico e adattabile, usato in filari urbani.',
 'ogni 7-10 giorni nel primo anno, poi occasionale', 'Pieno sole o mezza ombra',
 'albero', 'Facile', '{}',
 '{}', '{}',
 '[{"nome": "Irrigazione", "offset_days": 0, "recurrence_days": 7, "color": "blue"}, {"nome": "Potatura", "offset_days": 365, "recurrence_days": 365, "color": "purple"}]'::jsonb)

ON CONFLICT (slug) DO NOTHING;
